# Generated by Django 4.2.2 on 2023-07-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Name2', models.CharField(max_length=300)),
                ('Number', models.CharField(max_length=300)),
                ('Floor', models.CharField(max_length=300)),
            ],
        ),
    ]
